---
- name: Development Server
  hosts: all
  sudo: no
  roles:
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - foreman
    - repos
