---
- name: Install MongoDB
  apt: pkg={{ item }} state=installed
  with_items:
    - mongodb
  sudo: yes

- name: Copy mongodb config file to home directory
  copy: src=mongodb.conf dest=/etc
  sudo: yes
