apps:
   - script: index.js
     name: on-taskgraph
     cwd: /home/vagrant/src/on-taskgraph
   - script: index.js
     name: on-http
     cwd: /home/vagrant/src/on-http
   - script: index.js
     name: on-dhcp
     cwd: /home/vagrant/src/on-dhcp-proxy
   - script: index.js
     name: on-syslog
     cwd: /home/vagrant/src/on-syslog
   - script: index.js
     name: on-tftp
     cwd: /home/vagrant/src/on-tftp
