---
- name: retrieve microkernel and overlays from bintray
  get_url: url="https://bintray.com/artifact/download/rackhd/binary/builds/{{ item }}"
           dest="/home/vagrant/src/on-http/static/http/common/{{ item }}"
           validate_certs=no
           force=yes
  with_items:
   - base.trusty.3.13.0-32-generic.squashfs.img
   - discovery.overlay.cpio.gz
   - initrd.img-3.13.0-32-generic
   - vmlinuz-3.13.0-32-generic

- name: retrieve the latest bootloaders from bintray
  get_url: url="https://bintray.com/artifact/download/rackhd/binary/ipxe/{{ item }}"
           dest="/home/vagrant/src/on-tftp/static/tftp/{{ item }}"
           validate_certs=no
           force=yes
  with_items:
   - monorail.ipxe
   - monorail-efi32-snponly.efi
   - monorail-efi64-snponly.efi
   - undionly.kpxe

- name: make CoreOS directory for hosting CoreOS demonstration booting
  file: path=/home/vagrant/src/on-http/static/http/coreos state=directory

- name: retrieve CoreOS kernel and initrd
  get_url: url="http://stable.release.core-os.net/amd64-usr/current/{{ item }}"
           dest="/home/vagrant/src/on-http/static/http/coreos/{{ item }}"
           force=yes
  with_items:
   - coreos_production_pxe.vmlinuz
   - coreos_production_pxe_image.cpio.gz

# hacks for install CoreOS demo - to be replaced with proxy functionality
- name: make CoreOS directory for hosting CoreOS demonstration booting
  file: path=/home/vagrant/src/on-http/static/http/coreos/835.8.0 state=directory

- name: retrieve CoreOS kernel and initrd
  get_url: url="http://stable.release.core-os.net/amd64-usr/current/{{ item }}"
           dest="/home/vagrant/src/on-http/static/http/coreos/835.8.0/{{ item }}"
           force=yes
  with_items:
   - coreos_production_image.bin.bz2
   - coreos_production_image.bin.bz2.sig
