# Copyright 2016, EMC, Inc.

# DB & MSG

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"

rabbitmq: # 5672, 15672, 25672
  privileged: true
  image: rabbitmq:management
  net: "host"

# RackHD

on-dhcp-proxy: # 68, 68/udp, 4011
  privileged: true
  env_file: docker.env
  image: rackhd/on-dhcp-proxy
  net: "host"

on-http: # 80, 443
  privileged: true
  env_file: docker.env
  image: rackhd/on-http
  net: "host"

on-statsd: # 8125, 8125/udp
  privileged: true
  env_file: docker.env
  image: rackhd/on-statsd
  net: "host"

on-syslog: # 514, 514/udp
  privileged: true
  env_file: docker.env
  image: rackhd/on-syslog
  net: "host"

on-taskgraph: # 67, 67/udp
  privileged: true
  env_file: docker.env
  image: rackhd/on-taskgraph
  net: "host"
  volumes:
    - /RackHD/docker/isc-dhcp-server/defaults:/etc/defaults
    - /RackHD/docker/isc-dhcp-server/config:/etc/dhcp

on-tftp: # 69, 69/udp
  privileged: true
  env_file: docker.env
  image: rackhd/on-tftp
  net: "host"

# ELK

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /RackHD/docker/logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
