# Copyright 2016, EMC, Inc.

# DB & MSG

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"

rabbitmq: # 5672, 15672, 25672
  image: rabbitmq:management
  net: "host"
  privileged: true

# RackHD

on-dhcp-proxy: # 68, 68/udp, 4011
  image: rackhd/on-dhcp-proxy
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/monorail:/opt/monorail

on-http: # 80, 443
  image: rackhd/on-http
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/monorail:/opt/monorail

on-statsd: # 8125, 8125/udp
  image: rackhd/on-statsd
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/monorail:/opt/monorail

on-syslog: # 514, 514/udp
  image: rackhd/on-syslog
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/monorail:/opt/monorail

on-taskgraph: # 67, 67/udp
  image: rackhd/on-taskgraph
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/dhcp/config:/etc/dhcp
    - /RackHD/docker/dhcp/defaults:/etc/defaults
    - /RackHD/docker/monorail:/opt/monorail

on-tftp: # 69, 69/udp
  image: rackhd/on-tftp
  net: "host"
  privileged: true
  volumes:
    - /RackHD/docker/monorail:/opt/monorail

# ELK

elasticsearch:
  command: elasticsearch -Des.network.host=0.0.0.0
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  image: logstash:latest
  links:
    - elasticsearch
  ports:
    - "5000:5000"
  volumes:
    - /RackHD/docker/logstash/config:/etc/logstash/conf.d

kibana:
  image: kibana:latest
  links:
    - elasticsearch
  ports:
    - "5601:5601"
