elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /RackHD/docker/logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "8125:8125/udp"
  links:
    - elasticsearch
    - rabbitmq
    - on-http

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"

rabbitmq:
  image: rabbitmq:latest
  ports:
    - "15672:15672" # management port (guest:guest)
    # - "25672:25672" # cluster port
    - "5672:5672"   # amqp port
  # environment:
  #   - "RABBITMQ_NODENAME=my-rabbit"

on-taskgraph:
  privileged: true
  env_file: docker.env
  environment:
    amqp: "amqp://localhost"
    mongo: "mongodb://localhost/rackdh"
    statsd: "127.0.0.1:8125"
  image: on-taskgraph
  net: "host"
  # ports:
  #   - "67:67"
  #   - "67:67/udp"
  #   - "172.31.128.1:67:67"
  #   - "172.31.128.1:67:67/udp"

on-http:
  env_file: docker.env
  image: on-http
  ports:
    - "8080:80"
    - "8443:443"
    - "172.31.128.1:80:80"
    # - "172.31.128.1:443:443"
  links:
    - mongo
    - rabbitmq
  extra_hosts:
    - "on-http:127.0.0.1"

on-dhcp-proxy:
  privileged: true
  env_file: docker.env
  environment:
    amqp: "amqp://localhost"
    mongo: "mongodb://localhost/rackdh"
    statsd: "127.0.0.1:8125"
  image: on-dhcp-proxy
  net: "host"
  # ports:
  #   - "68:68"
  #   - "68:68/udp"
  #   - "4011:4011"
    # - "172.31.128.1:68:68"
    # - "172.31.128.1:68:68/udp"
    # - "172.31.128.1:4011:4011"

on-tftp:
  privileged: true
  env_file: docker.env
  environment:
    amqp: "amqp://localhost"
    mongo: "mongodb://localhost/rackdh"
    statsd: "127.0.0.1:8125"
  image: on-tftp
  net: "host"
  # ports:
  #   - "69:69"
  #   - "69:69/udp"
  #   - "172.31.128.1:69:69"
  #   - "172.31.128.1:69:69/udp"
  # links:
  #   - on-http
  #   - mongo
  #   - rabbitmq
  # extra_hosts:
  #   - "mongo:127.0.0.1"
  #   - "on-http:127.0.0.1"
  #   - "rabbitmq:127.0.0.1"

on-syslog:
  env_file: docker.env
  image: on-syslog
  ports:
    - "514:514"
  links:
    - on-http
    - mongo
    - rabbitmq
