---
- name: Init git submodules
  shell: git submodule init
  args:
    chdir: /home/vagrant/src
  sudo: yes

- name: Populate git submodules
  shell: git submodule update
  args:
    chdir: /home/vagrant/src
  sudo: yes

- name: Npm install Repos
  npm: path=/home/vagrant/src/{{ item }}
  with_items:
    - on-core
    - on-http
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-syslog
    - on-tasks
  sudo: yes 

- name: Make common static directory
  file: path=/home/vagrant/src/on-http/static/http/common state=directory
  sudo: yes
