---
- name: Download n Installer
  get_url: url=http://git.io/n-install dest=/tmp/n-install mode=0755
  register: download_n
  sudo: yes

- name: Install n
  shell: yes | N_PREFIX=/home/vagrant/n /tmp/n-install
  sudo: yes
  when: download_n|changed

- name: Install node
  shell: /home/vagrant/n/bin/n {{ item }}
  with_items:
#    - 4.1.1
#    - 0.12.7
    - 0.10.40
  sudo: yes
  when: download_n|changed
