---
- name: Get RackHD from source
  git: repo=https://github.com/rackhd/rackhd
       dest="{{ ansible_env.HOME }}/src"
       accept_hostkey=true
       version="{{ branch | default('master') }}"

- name: Update git repos with latest
  shell: git fetch --all --prune
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  with_items:
    - on-core
    - on-tasks
    - on-http
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-syslog
  sudo: yes

- name: Reset to the branch specified
  shell: git reset --hard {{ branch }}
  when: branch is defined
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  with_items:
    - on-core
    - on-tasks
    - on-http
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-syslog
  sudo: yes

- name: Npm install Repos
  npm: path="{{ ansible_env.HOME }}/src/{{ item }}"
       production=yes
  with_items:
    - on-syslog
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-http

- name: Make common static directory
  file: path="{{ ansible_env.HOME }}/src/on-http/static/http/common" state=directory

- name: Npm install apidoc
  shell: "npm install apidoc"
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-http"

- name: Render API docs for local reference
  shell: "npm run apidoc"
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-http"
